CREATE DATABASE fgiss;
USE fgiss;

--- student
CREATE TABLE ROLE (
    RoleID INT UNSIGNED NOT NULL,
    RoleName VARCHAR(50) NOT NULL,
    PRIMARY KEY (RoleID)
);

CREATE TABLE STUDENT (
    StudentID INT UNSIGNED NOT NULL,
    StudentName VARCHAR(100) NOT NULL,
    StudentEmail VARCHAR(255),
    Password VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(20),
    Email VARCHAR(255) NOT NULL,
    StudentName VARCHAR(255) NOT NULL,
    PRIMARY KEY (StudentID)
    RoleID INT UNSIGNED NOT NULL,
    PRIMARY KEY (StudentID),
    FOREIGN KEY (RoleID) REFERENCES ROLE(RoleID)
);

--- staff
CREATE TABLE STAFF (
    StaffID INT UNSIGNED NOT NULL,
    Department VARCHAR(100),
    Password VARCHAR(255) NOT NULL,
    Teacher_Email VARCHAR(255) NOT NULL,
    PRIMARY KEY (StaffID)
    RoleID INT UNSIGNED NOT NULL,
    PRIMARY KEY (StaffID),
    FOREIGN KEY (RoleID) REFERENCES ROLE(RoleID)
);

CREATE TABLE SUBJECT (
    SubjectID INT UNSIGNED NOT NULL,
    SubjectName VARCHAR(100) NOT NULL,
    SubjectCode VARCHAR(50),
    PRIMARY KEY (SubjectID)
);

CREATE TABLE CLASS (
    ClassID INT UNSIGNED NOT NULL,
    RoomNumber VARCHAR(20),
    Year INT(4) NOT NULL,
    PRIMARY KEY (ClassID)
);

CREATE TABLE ENROLLMENT (
    EnrollmentID INT UNSIGNED NOT NULL,
    StudentID INT UNSIGNED NOT NULL,
    ClassID INT UNSIGNED NOT NULL,
    Date_of_enrollment DATE NOT NULL,
    PRIMARY KEY (EnrollmentID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID),
    FOREIGN KEY (ClassID) REFERENCES CLASS(ClassID)
);

--- assignment
CREATE TABLE ASSIGNMENT (
    AssignmentID INT UNSIGNED NOT NULL,
    Title VARCHAR(244) NOT NULL,
    SubjectName VARCHAR(100) NOT NULL,
    MaxScore DECIMAL(8,2) NOT NULL DEFAULT 100.00,
    Title VARCHAR(255) NOT NULL,
    MaxScore DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (AssignmentID)
);

--- quiz
CREATE TABLE QUIZ (
    QuizID INT UNSIGNED NOT NULL,
    Title VARCHAR(244) NOT NULL,
    SubjectName VARCHAR(100) NOT NULL,
    MaxScore DECIMAL(8,2) NOT NULL DEFAULT 100.00,
    Title VARCHAR(255) NOT NULL,
    MaxScore DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (QuizID)
);

--- exam
CREATE TABLE EXAM (
    ExamID INT UNSIGNED NOT NULL,
    Title VARCHAR(244) NOT NULL,
    SubjectName VARCHAR(100) NOT NULL,
    MaxScore DECIMAL(8,2) NOT NULL DEFAULT 100.00,
    Title VARCHAR(255) NOT NULL,
    MaxScore DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (ExamID)
);

--- enrollment
CREATE TABLE ENROLLMENT (
    EnrollmentID INT UNSIGNED NOT NULL,
    StudentID INT UNSIGNED NOT NULL,
    ClassID INT UNSIGNED NOT NULL,
    Date_of_enrollment DATE NOT NULL DEFAULT CURRENT_DATE,
    PRIMARY KEY (EnrollmentID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID)
);

--- grade
CREATE TABLE GRADE (
    GradeID INT UNSIGNED NOT NULL,
    Score DECIMAL(7,1) NOT NULL,
    Score DECIMAL(5,2) NOT NULL,
    FinalGrade DECIMAL(5,2) NOT NULL,
    SubjectName VARCHAR(100) NOT NULL,
    StudentID INT UNSIGNED NOT NULL,
    AssignmentID INT UNSIGNED,
    QuizID INT UNSIGNED,
@@ -73,4 +86,49 @@ CREATE TABLE GRADE (
    FOREIGN KEY (AssignmentID) REFERENCES ASSIGNMENT(AssignmentID),
    FOREIGN KEY (QuizID) REFERENCES QUIZ(QuizID),
    FOREIGN KEY (ExamID) REFERENCES EXAM(ExamID)
);

CREATE TABLE SYLLABUS (
    SyllabusID INT UNSIGNED NOT NULL,
    QuizWeight DECIMAL(5,2),
    ExamWeight DECIMAL(5,2),
    AssignmentWeight DECIMAL(5,2) NOT NULL,
    SubjectID INT UNSIGNED,
    PRIMARY KEY (SyllabusID),
    FOREIGN KEY (SubjectID) REFERENCES SUBJECT(SubjectID)
);

CREATE TABLE CLASS_SUBJECT (
    ClassSubjectID INT UNSIGNED NOT NULL,
    ClassID INT UNSIGNED NOT NULL,
    SubjectID INT UNSIGNED NOT NULL,
    Year INT(4) NOT NULL,
    PRIMARY KEY (ClassSubjectID),
    FOREIGN KEY (ClassID) REFERENCES CLASS(ClassID),
    FOREIGN KEY (SubjectID) REFERENCES SUBJECT(SubjectID)
);

CREATE TABLE CLASS_STAFF (
    Class_StaffID INT UNSIGNED NOT NULL,
    ClassID INT UNSIGNED NOT NULL,
    StaffID INT UNSIGNED NOT NULL,
    PRIMARY KEY (Class_StaffID),
    FOREIGN KEY (ClassID) REFERENCES CLASS(ClassID),
    FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID)
);

CREATE TABLE INTERVENTION (
    InterventionID INT UNSIGNED NOT NULL,
    IdentifiedIssue VARCHAR(255) NOT NULL,
    ActionPlan TEXT NOT NULL,
    PRIMARY KEY (InterventionID)
);

CREATE TABLE VIOLATION (
    ViolationID INT UNSIGNED NOT NULL,
    ReportSummary VARCHAR(500) NOT NULL,
    ViolationType VARCHAR(100) NOT NULL,
    Description TEXT,
    DateTimeOccurred TIMESTAMP,
    PRIMARY KEY (ViolationID)