# Generated by Django 5.2.1 on 2026-05-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentGrades', '0003_alter_grade_score_subject_alter_grade_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['grade_level', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
