# Generated by Django 6.0.4 on 2026-05-01 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("StudentRecords", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="Grade_level",
            new_name="grade_level",
        ),
    ]
