# Generated by Django 4.2.29 on 2026-05-03 18:46

import StudentRecords.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentRecords', '0003_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[StudentRecords.models.validate_fgiss_email]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_student_number', message='Student number must be in the format stuXXXX (e.g., stu0001)', regex='^stu\\d{4}$')]),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_student_name'),
        ),
    ]
