# Generated by Django 5.2.1 on 2026-05-06 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentRecords', '0004_alter_student_email_alter_student_student_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('Academic', 'Academic'), ('Behavioral', 'Behavioral'), ('Other', 'Other')], max_length=20)),
                ('incident_date', models.DateField()),
                ('report_content', models.TextField()),
                ('reported_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='StudentRecords.student')),
            ],
        ),
    ]
