# Generated by Django 6.0.4 on 2026-05-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Syllabus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("topics", models.TextField(blank=True)),
            ],
        ),
    ]
