# Generated by Django 4.2.29 on 2026-05-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CourseSyllabi", "0002_alter_syllabus_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="syllabus",
            name="grade_level",
            field=models.CharField(
                choices=[
                    ("Grade 1", "Grade 1"),
                    ("Grade 2", "Grade 2"),
                    ("Grade 3", "Grade 3"),
                    ("Grade 4", "Grade 4"),
                    ("Grade 5", "Grade 5"),
                    ("Grade 6", "Grade 6"),
                ],
                default="Grade 1",
                max_length=20,
            ),
        ),
    ]
