# Generated by Django 4.2.29 on 2026-05-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CourseSyllabi", "0003_syllabus_grade_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="syllabus",
            name="course_code",
        ),
    ]
