# Generated by Django 4.2.29 on 2026-05-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassSchedules', '0002_alter_classschedule_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
