# Generated by Django 4.2.29 on 2026-05-03 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentGrades', '0004_alter_subject_options_subject_order'),
        ('ClassSchedules', '0003_remove_classschedule_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='class_name',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='StudentGrades.subject'),
        ),
    ]
