# Generated by Django 4.2.29 on 2026-05-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassSchedules', '0004_remove_classschedule_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
