# Generated by Django 6.0.4 on 2026-05-01 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("CourseSyllabi", "0001_initial"),
        ("ExamSchedules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topics_covered", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverages",
                        to="ExamSchedules.examschedule",
                    ),
                ),
                (
                    "syllabus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="CourseSyllabi.syllabus",
                    ),
                ),
            ],
        ),
    ]
