# Generated by Django 6.0.4 on 2026-05-01 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("StudentRecords", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviourIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("action_taken", models.TextField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="StudentRecords.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterventionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("Academic Support", "Academic Support"),
                            ("Behavioral Modification", "Behavioral Modification"),
                            ("Social-Emotional Learning", "Social-Emotional Learning"),
                            ("Attendance Contract", "Attendance Contract"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("review_date", models.DateField()),
                ("primary_goal", models.TextField()),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_plan",
                        to="StudentRecords.student",
                    ),
                ),
            ],
        ),
    ]
